import React, { useState } from 'react';
import { Download, Maximize2, RotateCcw, X, Loader2, Image as ImageIcon } from 'lucide-react';
import { Attachment } from '@/lib/chat/types';
import { cn } from '@/lib/utils';
import { Button } from '@/components/ui/button';
import { toast } from 'sonner';

interface GeneratedImageProps {
  attachment: Attachment;
  onRegenerate?: () => void;
  className?: string;
}

export function GeneratedImage({ attachment, onRegenerate, className }: GeneratedImageProps) {
  const [isFullscreen, setIsFullscreen] = useState(false);
  const [isLoaded, setIsLoaded] = useState(false);

  const handleDownload = async () => {
    try {
      const response = await fetch(attachment.url);
      const blob = await response.blob();
      const url = window.URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = attachment.name || 'ramaibot-generated-image.webp';
      document.body.appendChild(a);
      a.click();
      window.URL.revokeObjectURL(url);
      document.body.removeChild(a);
      toast.success("Image download started");
    } catch (error) {
      toast.error("Failed to download image");
    }
  };

  if (attachment.status === 'uploading' || attachment.status === 'processing') {
    return (
      <div className={cn("relative aspect-square w-full max-w-md glass-strong rounded-2xl flex flex-col items-center justify-center gap-4 border-white/5 overflow-hidden", className)}>
        <div className="absolute inset-0 bg-primary/5 animate-pulse" />
        <Loader2 className="w-8 h-8 text-primary animate-spin relative z-10" />
        <span className="text-xs font-bold uppercase tracking-widest text-muted-foreground/60 animate-pulse relative z-10">
          Generating Excellence...
        </span>
      </div>
    );
  }

  if (attachment.status === 'failed') {
    return (
      <div className={cn("w-full max-w-md glass-strong rounded-2xl p-6 border-red-500/20 bg-red-500/5 flex flex-col items-center gap-3", className)}>
        <ImageIcon className="w-8 h-8 text-red-400 opacity-50" />
        <span className="text-sm font-medium text-red-400">Failed to generate image</span>
        {attachment.error && <p className="text-[10px] text-red-400/60 text-center">{attachment.error}</p>}
        {onRegenerate && (
          <Button variant="ghost" size="sm" onClick={onRegenerate} className="mt-2 text-xs uppercase font-bold tracking-widest">
            <RotateCcw className="w-3.5 h-3.5 mr-2" />
            Retry
          </Button>
        )}
      </div>
    );
  }

  return (
    <>
      <div className={cn("group relative w-full max-w-md rounded-2xl overflow-hidden glass border-white/5 transition-all duration-500 hover:shadow-2xl hover:shadow-primary/5", className)}>
        {!isLoaded && (
          <div className="absolute inset-0 flex items-center justify-center bg-zinc-900/50">
            <Loader2 className="w-6 h-6 text-primary animate-spin" />
          </div>
        )}
        <img 
          src={attachment.url} 
          alt="Generated by Ramaibot"
          className={cn(
            "w-full h-auto object-cover transition-all duration-700",
            isLoaded ? "opacity-100 scale-100" : "opacity-0 scale-105"
          )}
          onLoad={() => setIsLoaded(true)}
          loading="lazy"
        />
        
        <div className="absolute inset-0 bg-black/40 opacity-0 group-hover:opacity-100 transition-opacity duration-300 flex items-end justify-between p-4 backdrop-blur-[2px]">
          <div className="flex gap-2">
            <Button 
              size="icon" 
              variant="secondary" 
              className="w-9 h-9 rounded-xl glass bg-white/10 border-white/10 hover:bg-white/20 text-white"
              onClick={() => setIsFullscreen(true)}
              aria-label="Fullscreen preview"
            >
              <Maximize2 className="w-4 h-4" />
            </Button>
            <Button 
              size="icon" 
              variant="secondary" 
              className="w-9 h-9 rounded-xl glass bg-white/10 border-white/10 hover:bg-white/20 text-white"
              onClick={handleDownload}
              aria-label="Download image"
            >
              <Download className="w-4 h-4" />
            </Button>
          </div>
          {onRegenerate && (
            <Button 
              size="icon" 
              variant="secondary" 
              className="w-9 h-9 rounded-xl glass bg-white/10 border-white/10 hover:bg-white/20 text-white"
              onClick={onRegenerate}
              aria-label="Regenerate image"
            >
              <RotateCcw className="w-4 h-4" />
            </Button>
          )}
        </div>
      </div>

      {isFullscreen && (
        <div className="fixed inset-0 z-[100] bg-black/95 backdrop-blur-2xl flex items-center justify-center p-4 animate-in fade-in duration-300">
          <Button 
            variant="ghost" 
            size="icon" 
            className="absolute top-6 right-6 text-white hover:bg-white/10 rounded-full w-12 h-12"
            onClick={() => setIsFullscreen(false)}
          >
            <X className="w-8 h-8" />
          </Button>
          
          <img 
            src={attachment.url} 
            alt="Generated by Ramaibot"
            className="max-w-full max-h-full object-contain rounded-lg shadow-2xl animate-in zoom-in-95 duration-500"
          />
          
          <div className="absolute bottom-10 left-1/2 -translate-x-1/2 flex gap-4">
             <Button 
              onClick={handleDownload}
              className="glass bg-white/10 border-white/10 hover:bg-white/20 text-white px-6 py-6 rounded-2xl font-bold uppercase tracking-widest text-xs"
            >
              <Download className="w-4 h-4 mr-2" />
              Download High Res
            </Button>
          </div>
        </div>
      )}
    </>
  );
}
