// This file is auto-generated by Lovable. Keep provider initialization lazy so SSR/Cloudflare
// does not execute browser-auth setup while importing the route tree.
import { createLovableAuth } from "@lovable.dev/cloud-auth-js";
import { supabase } from "../supabase/client";

type SignInOptions = {
  redirect_uri?: string;
  extraParams?: Record<string, string>;
};

let lovableAuth: ReturnType<typeof createLovableAuth> | undefined;

function getLovableAuth() {
  if (!lovableAuth) lovableAuth = createLovableAuth();
  return lovableAuth;
}

export const lovable = {
  auth: {
    signInWithOAuth: async (provider: "google" | "apple" | "microsoft" | "lovable", opts?: SignInOptions) => {
      const result = await getLovableAuth().signInWithOAuth(provider, {
        ...opts,
        extraParams: {
          ...opts?.extraParams,
        },
      });

      if (result.redirected) return result;
      if (result.error) return result;

      try {
        await supabase.auth.setSession(result.tokens);
      } catch (e) {
        return { error: e instanceof Error ? e : new Error(String(e)) };
      }
      return result;
    },
  },
};
