/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalyzeFilesIndexRouteImport } from './routes/analyze-files/index'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthVerifyRouteImport } from './routes/auth/verify'
import { Route as ExploreModelsIndexRouteImport } from './routes/explore-models/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as ApiChatStreamRouteImport } from './routes/api/chat/stream'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyzeFilesIndexRoute = AnalyzeFilesIndexRouteImport.update({
  id: '/analyze-files/',
  path: '/analyze-files/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyRoute = AuthVerifyRouteImport.update({
  id: '/auth/verify',
  path: '/auth/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreModelsIndexRoute = ExploreModelsIndexRouteImport.update({
  id: '/explore-models/',
  path: '/explore-models/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatStreamRoute = ApiChatStreamRouteImport.update({
  id: '/api/chat/stream',
  path: '/api/chat/stream',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/analyze-files/': typeof AnalyzeFilesIndexRoute
  '/explore-models/': typeof ExploreModelsIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/api/chat/stream': typeof ApiChatStreamRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/analyze-files': typeof AnalyzeFilesIndexRoute
  '/explore-models': typeof ExploreModelsIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/api/chat/stream': typeof ApiChatStreamRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/analyze-files/': typeof AnalyzeFilesIndexRoute
  '/explore-models/': typeof ExploreModelsIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/api/chat/stream': typeof ApiChatStreamRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/callback'
    | '/auth/verify'
    | '/analyze-files/'
    | '/explore-models/'
    | '/projects/'
    | '/api/chat/stream'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/callback'
    | '/auth/verify'
    | '/analyze-files'
    | '/explore-models'
    | '/projects'
    | '/api/chat/stream'
  id:
    | '__root__'
    | '/'
    | '/auth/callback'
    | '/auth/verify'
    | '/analyze-files/'
    | '/explore-models/'
    | '/projects/'
    | '/api/chat/stream'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthVerifyRoute: typeof AuthVerifyRoute
  AnalyzeFilesIndexRoute: typeof AnalyzeFilesIndexRoute
  ExploreModelsIndexRoute: typeof ExploreModelsIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  ApiChatStreamRoute: typeof ApiChatStreamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyze-files/': {
      id: '/analyze-files/'
      path: '/analyze-files'
      fullPath: '/analyze-files/'
      preLoaderRoute: typeof AnalyzeFilesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verify': {
      id: '/auth/verify'
      path: '/auth/verify'
      fullPath: '/auth/verify'
      preLoaderRoute: typeof AuthVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore-models/': {
      id: '/explore-models/'
      path: '/explore-models'
      fullPath: '/explore-models/'
      preLoaderRoute: typeof ExploreModelsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat/stream': {
      id: '/api/chat/stream'
      path: '/api/chat/stream'
      fullPath: '/api/chat/stream'
      preLoaderRoute: typeof ApiChatStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthVerifyRoute: AuthVerifyRoute,
  AnalyzeFilesIndexRoute: AnalyzeFilesIndexRoute,
  ExploreModelsIndexRoute: ExploreModelsIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  ApiChatStreamRoute: ApiChatStreamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
